plugins {
    id 'java'
}

group = 'net.anawesomguy'
version = version

sourceSets {
    test {
        compileClasspath -= sourceSets.main.compileClasspath
        runtimeClasspath -= sourceSets.main.runtimeClasspath
    }
}

java.toolchain.languageVersion = JavaLanguageVersion.of 8

compileJava {
    sourceCompatibility = targetCompatibility = JavaVersion.VERSION_1_5
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs.addAll(
            '-g:none', // disable debug stuffs
            '-Xlint:-options' // supress warning about java 5
    )
}

tasks.withType(Jar).configureEach {
    manifest.attributes(['Premain-Class': 'classdump.Dumper'])
    from 'LICENSE'
}

tasks.register('runTest', JavaExec) {
    dependsOn jar
    group 'verification'
    classpath sourceSets.test.runtimeClasspath
    jvmArgs '-javaagent:' + jar.archiveFile.get() + '=debug'
    jvmArgs '-Xmx2M'
    mainClass = 'net.anawesomguy.clsdump.test.Main'
    workingDir 'build/test/'
    workingDir.deleteDir()
    workingDir.mkdirs()
}