name: Build and Test

on: [pull_request, push]

jobs:
  build_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Test
        run: ./gradlew runMainTest
  build_5:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Test
        run: ./gradlew runJava5Test
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Upload build artifacts
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: build/libs/*.jar