name: Build and Test

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 8

      - name: setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: run test
        run: |
          chmod +x ./gradlew
          ./gradlew runTest

      - name: upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: build/libs/*.jar